pipeline {
    agent any

    tools {
        jdk 'jdk25.0.4'
        maven 'Maven3'
    }

    stages {
        stage('build') {
            steps {
                // WRONG on Windows:
                // sh 'mvn clean package'

                // CORRECT on Windows:
                bat 'mvn clean package'
            }
        }
    }
}
